baseURL = '/'
languageCode = 'en-us'
title = 'Komputasi Geofisika'
theme = 'hugo-PaperMod'

[params.homeInfoParams]
Title = "Hi thereðŸ‘‹"
Content = "Can be Info, links, about..."

[[params.socialIcons]]
name = "Twitter"
url = "https://twitter.com/vysf__"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/vysf"
